### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by oec** [pions/turn#34]
`simple-turn` doesn't compile (with commit eeda63bc37cd8fcfd5bfad4c8c7b26ee935e4e1f):

```
% go version                                    
go version go1.11.5 linux/amd64
% cd ~/src/github.com/pions/turn/cmd/simple-turn
% go build
# github.com/pions/turn/internal/client
../../internal/client/stun.go:34:26: cannot use conn (type *ipv4.PacketConn) as type net.PacketConn in argument to stun.BuildAndSend:
	*ipv4.PacketConn does not implement net.PacketConn (wrong type for ReadFrom method)
		have ReadFrom([]byte) (int, *ipv4.ControlMessage, net.Addr, error)
		want ReadFrom([]byte) (int, net.Addr, error)
# github.com/pions/turn/internal/allocation
../../internal/allocation/allocation.go:206:32: cannot use a.TurnSocket (type *ipv4.PacketConn) as type net.PacketConn in argument to stun.BuildAndSend:
	*ipv4.PacketConn does not implement net.PacketConn (wrong type for ReadFrom method)
		have ReadFrom([]byte) (int, *ipv4.ControlMessage, net.Addr, error)
		want ReadFrom([]byte) (int, net.Addr, error)
```

I ran `go get -u golang.org/x/net/...` to make sure I have the latest version of `net/ipv4`.  The build still fails for simple-turn.

**Comment by backkem** [comment]
Hi @oec, This error occurs because out are using a newer version of `pions/stun`. We're now using [go modules](https://github.com/golang/go/wiki/Modules) in order to download the correct dependencies. In order to enable modules you can set the following environment variable: `GO111MODULE=on` before building the example. This will become the default in future versions of Go.
If you don't want to use modules support for some reason, you could manually check out the correct versions of the dependencies. These can be found in `go.mod` file:
https://github.com/pions/turn/blob/eeda63bc37cd8fcfd5bfad4c8c7b26ee935e4e1f/go.mod#L4-L6

**Comment by oec** [comment]
Hi @backkem, thanks for the quick response!  Indeed, with
```
% GO111MODULE=on go build
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/pions/stun v0.1.0
go: finding golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go: finding golang.org/x/net v0.0.0-20190119204137-ed066c81e75e
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/stretchr/objx v0.1.0
go: downloading github.com/pions/stun v0.1.0
go: downloading golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go: downloading github.com/pkg/errors v0.8.1
``` 
`simple-turn` compiles.  I do use go modules myself but did not think of enabling them here, sorry for the stir.  Maybe a hint in the Readme.md would be helpful, though.
